
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

duckdns:
  domain: maison-kuhn
  access_token: !secret duckdns_token

http:
  base_url: https://maison-kuhn.duckdns.org
  ssl_certificate: /config/swag/etc/letsencrypt/live/maison-kuhn.duckdns.org/fullchain.pem
  ssl_key: /config/swag/etc/letsencrypt/live/maison-kuhn.duckdns.org/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
