version: '3.4'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2025.4"
    volumes:
      - ./config/homeassistant:/config
      - ./config/swag:/config/swag
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    ports:
      - 8123:8123
      - ${EMULATED_HUE_LISTEN_PORT}:${EMULATED_HUE_LISTEN_PORT}
    devices:
      - ${ZIGBEE_COORDINATOR_PATH}:${ZIGBEE_COORDINATOR_PATH}
    environment:
      - DUCKDNS_DOMAIN=${DUCKDNS_DOMAIN}
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - LAN_IP_ADDRESS=${LAN_IP_ADDRESS}
      - EMULATED_HUE_LISTEN_PORT=${EMULATED_HUE_LISTEN_PORT}
      - HA_NAME=${HA_NAME}
      - HA_HTTP_SSL_CERTIFICATE_LOCATION=/config/swag/etc/letsencrypt/live/${DUCKDNS_DOMAIN}.duckdns.org/fullchain.pem
      - HA_HTTP_SSL_KEY_LOCATION=/config/swag/etc/letsencrypt/live/${DUCKDNS_DOMAIN}.duckdns.org/privkey.pem
      - HA_LATITUDE=${HA_LATITUDE}
      - HA_LONGITUDE=${HA_LONGITUDE}
      - HA_ELEVATION=${HA_ELEVATION}
      - HA_COUNTRY=${HA_COUNTRY}
      - HA_EXTERNAL_URL=https://${DUCKDNS_DOMAIN}.duckdns.org:8123
      - HA_INTERNAL_URL=https://${LAN_IP_ADDRESS}:8123
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - URL=${DUCKDNS_DOMAIN}.duckdns.org
      - SUBDOMAINS=
      - VALIDATION=duckdns
      - CERTPROVIDER=zerossl #optional
      - DNSPLUGIN=cloudflare #optional
      - DUCKDNSTOKEN=${DUCKDNS_TOKEN}
      - EMAIL=terry.dervaux@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./config/swag:/config
    ports:
      - 443:443
#      - 80:80 #optional
    restart: unless-stopped
  esphome:
    container_name: esphome
    image: "esphome/esphome:2022.10.2"
    volumes:
      - ./config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6052:6052
    restart: unless-stopped
    privileged: true
    network_mode: host
  mqtt-broker:
    container_name: mqtt-broker
    image: "eclipse-mosquitto:2.0.15"
    restart: unless-stopped
    ports: 
      - 1883:1883
    volumes:
#      - "./config/swag/etc/letsencrypt/live/${DUCKDNS_DOMAIN}.duckdns.org/fullchain.pem:/mosquitto/config/fullchain.pem"
#      - "./config/swag/etc/letsencrypt/live/${DUCKDNS_DOMAIN}.duckdns.org/privkey.pem:/mosquitto/config/privkey.pem"
      - "./config/mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "./config/mqtt/passwd:/mosquitto/config/passwd"
      - "./config/mqtt/data:/mosquitto/data"
      - "./config/mqtt/log:/mosquitto/log"
