- id: '1689318305780'
  alias: Watering system auto turn off 2min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.relay_switch
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.relay_switch
  mode: single
