default_config:
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  name: !env_var HA_NAME
  latitude: !env_var HA_LATITUDE
  longitude: !env_var HA_LONGITUDE
  elevation: !env_var HA_ELEVATION
  unit_system: metric
  temperature_unit: C
  country: !env_var HA_COUNTRY
  time_zone: "Europe/Paris"
  external_url: !env_var HA_EXTERNAL_URL
  internal_url: !env_var HA_INTERNAL_URL
  legacy_templates: false

duckdns:
  domain: !env_var DUCKDNS_DOMAIN
  access_token: !env_var DUCKDNS_TOKEN

http:
  ssl_certificate: !env_var HA_HTTP_SSL_CERTIFICATE_LOCATION
  ssl_key: !env_var HA_HTTP_SSL_KEY_LOCATION

wake_on_lan:

switch:
  - platform: wake_on_lan
    name: "DESKTOP-KUHN-ETHERNET"
    mac: F0:2F:74:85:9D:D6
    host: 192.168.1.12
    broadcast_address: 192.168.1.255
    broadcast_port: 9
  - platform: wake_on_lan
    name: "DESKTOP-KUHN-WIFI"
    mac: 68:54:5A:07:05:9E
    host: 192.168.1.33
    broadcast_address: 192.168.1.255
    broadcast_port: 9
  - platform: command_line
    switches:
      relay_switch:
        command_on: 'curl -X POST http://192.168.1.47/relay -d relayActivation=true'
        command_off: 'curl -X POST http://192.168.1.47/relay -d relayActivation=false'
        command_state: 'curl -X GET http://192.168.1.47/relay'
        value_template: '{{ value == "{relayActivation=true}" }}'
        friendly_name: Watering System

samsungtv:
  - host: 192.168.1.19
    turn_on_action:
      - service: wake_on_lan.send_magic_packet
        data:
          mac: E4:7D:BD:97:70:14

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_15m
      - type: throughput_network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

# MQTT Broker (eclipse-mosquitto)
mqtt:
  broker: !env_var MQTT_URL
  port: 1883
  username: !env_var MQTT_LOGIN
  password: !env_var MQTT_PASSWORD
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: "homeassistant/status"
    payload: "online"
  will_message:
    topic: "homeassistant/status"
    payload: "offline"

# ZSONOFF Zigbee 3.0 USB Dongle Plus V2
zha:
  zigpy_config:
    ota:
      ikea_provider: false                       # Auto update Trådfri devices

# Emulated Hue for Alexa connection
emulated_hue:
  type: alexa
  host_ip: !env_var LAN_IP_ADDRESS
  listen_port: !env_var EMULATED_HUE_LISTEN_PORT
  expose_by_default: true

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: info

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
