
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

duckdns:
  domain: maison-kuhn
  access_token: !secret duckdns_token

http:
  base_url: https://maison-kuhn.duckdns.org
  ssl_certificate: /config/swag/etc/letsencrypt/live/maison-kuhn.duckdns.org/fullchain.pem
  ssl_key: /config/swag/etc/letsencrypt/live/maison-kuhn.duckdns.org/privkey.pem

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_15m
      - type: throughput_network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
