default_config:
# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  name: !env_var HA_NAME
  latitude: !env_var HA_LATITUDE
  longitude: !env_var HA_LONGITUDE
  elevation: !env_var HA_ELEVATION
  unit_system: metric
  temperature_unit: C
  time_zone: "Europe/Paris"
  external_url: !env_var HA_EXTERNAL_URL
  internal_url: !env_var HA_INTERNAL_URL
  legacy_templates: false

duckdns:
  domain: !env_var DUCKDNS_DOMAIN
  access_token: !env_var DUCKDNS_TOKEN

http:
  ssl_certificate: !env_var HA_HTTP_SSL_CERTIFICATE_LOCATION
  ssl_key: !env_var HA_HTTP_SSL_KEY_LOCATION

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: disk_use
      - type: disk_free
      - type: memory_use_percent
      - type: memory_use
      - type: memory_free
      - type: swap_use
      - type: swap_free
      - type: load_15m
      - type: throughput_network_out
        arg: eth0
      - type: throughput_network_in
        arg: eth0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
  - platform: glances
    name: raspberry-salon
    host: 192.168.1.17
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'cpu_use_percent'
      - 'sensor_temp'

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
