name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    env:
      working-directory: ./config
    steps:
      - uses: "actions/checkout@v2"
      - uses: home-assistant/actions/hassfest@master